cloud:
  aws:
    credentials:
      access-key: AKIAX5MMOW2NIJV2DP6L
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: awsexpressdeliverystorage


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080